/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CanvasAction: typeof import('./src/components/container/CanvasAction.vue')['default']
    CanvasBox: typeof import('./src/components/builtin/CanvasBox.vue')['default']
    CanvasCol: typeof import('./src/components/builtin/CanvasCol.vue')['default']
    CanvasCollection: typeof import('./src/components/builtin/CanvasCollection.vue')['default']
    CanvasContainer: typeof import('./src/components/container/CanvasContainer.vue')['default']
    CanvasDivider: typeof import('./src/components/container/CanvasDivider.vue')['default']
    CanvasDragItem: typeof import('./src/components/container/CanvasDragItem.vue')['default']
    CanvasEmpty: typeof import('./src/components/render/CanvasEmpty.vue')['default']
    CanvasFooter: typeof import('./src/components/container/CanvasFooter.vue')['default']
    CanvasIcon: typeof import('./src/components/builtin/CanvasIcon.vue')['default']
    CanvasImg: typeof import('./src/components/builtin/CanvasImg.vue')['default']
    CanvasMenu: typeof import('./src/components/container/CanvasMenu.vue')['default']
    CanvasPlaceholder: typeof import('./src/components/builtin/CanvasPlaceholder.vue')['default']
    CanvasResize: typeof import('./src/components/container/CanvasResize.vue')['default']
    CanvasResizeBorder: typeof import('./src/components/container/CanvasResizeBorder.vue')['default']
    CanvasRow: typeof import('./src/components/builtin/CanvasRow.vue')['default']
    CanvasRowColContainer: typeof import('./src/components/builtin/CanvasRowColContainer.vue')['default']
    CanvasSlot: typeof import('./src/components/builtin/CanvasSlot.vue')['default']
    CanvasText: typeof import('./src/components/builtin/CanvasText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortCutPopover: typeof import('./src/components/container/shortCutPopover.vue')['default']
  }
}
